### PR TITLE
added new site for explore country data in charts

### PR DESCRIPTION
**Pull request by Virous77**
---
name: feat: Globe Graph
about: Globe Graph is a web app that visualizes the countries data like GDP, GDP per capita, and population in different years using many charts.
labels: feature

---

## Describe the awesome thing you want to add

**What is it?** 
Globe Graph is a web app that visualizes the countries data like GDP, GDP per capita, and population in different years using many charts.

**What category does it belong to?** (Libs and Components, Apps, Ports, Design System, Boilerplates/Templates)
Apps

**Anything else? (optional)** (e.g. screenshots, additional information, etc.)

## Checklist

- [✔️] I checked that it is in alphabetical order.
- [✔️] I have checked that the awesome thing is not already listed.
- [✔️] I have provided a clear and concise description of the awesome thing.
- [✔️] I have provided a link to the awesome thing.
- [✔️] I have assigned the correct category to the awesome thing.

**Please note:** If you are adding a new category, you will need to create a new section in the `README.md` file. Please make sure to update the table of contents as well.

**Important:** The idea of this repository is to bring together free projects for open-source contributions. If the proposed addition is an entirely paid project, the PR will be closed.

### CODE REVIEW

**Comment by avalynndev** [comment]
ngl recommend u to keep the name in small-case i.e `country-data-in-charts`

**Comment by Virous77** [comment]
> ngl recommend u to keep the name in small-case i.e `country-data-in-charts`

Do you mean the name of site or here for docs?

**Comment by avalynndev** [comment]
> > ngl recommend u to keep the name in small-case i.e `country-data-in-charts`
> 
> Do you mean the name of site or here for docs?

i mean over here..
- [country-data-in-charts](https://globe-graph.vercel.app/) - Globe graph is a web app that visualizes the countries data like GDP, GDP per capita, and population in different years using many charts.
keep this..

**Comment by avalynndev** [comment]
and @Virous77 your graph is starting from 2023 and going to the start date.. shouldn't it start from the start date and go till 2023?

**Comment by Virous77** [comment]
@avalynndev I have added default from 2010- to 2024. You can select years and country as per your need. Also It should always show the latest data first thats why when we show data it like TO-FROM.

**Comment by avalynndev** [comment]
> @avalynndev I have added default from 2010- to 2024. You can select years and country as per your need. Also It should always show the latest data first thats why when we show data it like TO-FROM.

great work.. im still studying and this website is loved by my teacher.. thx for this project

**Comment by avalynndev** [comment]
- [country-data-in-charts](https://globe-graph.vercel.app/) - Globe graph is a web app that visualizes the countries data like GDP, GDP per capita, and population in different years using many charts.

keep this in the readme..

**Comment by Virous77** [comment]
@birobirobiro  it's done.

**Pull request merged**
