### PR TITLE
chore: add motion primitives

### PR DESCRIPTION
**Pull request by Pedro-phd**
---
name: feat: Add **Motion Primitives**

about: Add a new lib for animated components

labels: feature

---

## Describe the awesome thing you want to add

Beautifully designed motions components. Easy copy-paste. Customizable. Open Source. Built for engineers and designers.

**What is it?** 

A lib of animated components

**What category does it belong to?** (Libs and Components, Apps, Ports, Design System, Boilerplates/Templates)
Libs and Components

**Anything else? (optional)** (e.g. screenshots, additional information, etc.)

## Checklist

- [x] I checked that it is in alphabetical order.
- [x] I have checked that the awesome thing is not already listed.
- [x] I have provided a clear and concise description of the awesome thing.
- [x] I have provided a link to the awesome thing.
- [x] I have assigned the correct category to the awesome thing.

**Please note:** If you are adding a new category, you will need to create a new section in the `README.md` file. Please make sure to update the table of contents as well.

**Important:** The idea of this repository is to bring together free projects for open-source contributions. If the proposed addition is an entirely paid project, the PR will be closed.

### CODE REVIEW

**Review by birobirobiro — COMMENTED** [review]
Firstly, thank you for the contribution. I took a look at the repository and the code and I don't think it's using anything related to shadcn/ui.

The idea of ​​this repo is to bring together components, libs, sites, platforms that use shadcn/ui

If I was mistaken, let me know before closing the PR.

**Comment by Pedro-phd** [comment]
Hello @birobirobiro , sorry!

This library really has no direct correlation to shadcn.

I looked at some examples listed and realized that some of them had no correlation with shadcn but were very useful for ui & ux, I thought this would be a good example of that too.

But I completely understand your point of view, I just thought it would be of great use to people, as this repository has become an excellent starting point for frontend development.

Anyway, sorry for the mistake!

**Comment by birobirobiro** [comment]
> Hello @birobirobiro , sorry!
> 
> This library really has no direct correlation to shadcn.
> 
> I looked at some examples listed and realized that some of them had no correlation with shadcn but were very useful for ui & ux, I thought this would be a good example of that too.
> 
> But I completely understand your point of view, I just thought it would be of great use to people, as this repository has become an excellent starting point for frontend development.
> 
> Anyway, sorry for the mistake!

That it! No problem, I thought the one you sent was a great reference, it's already in my favorites hehehe

If you want to send a PR removing those that are not related to shadcn/ui, you can send it, because the idea of ​​this repository is to really aggregate content that is related to it.

**Comment by Pedro-phd** [comment]
Never, I think everything on this list is of great quality, it would be a crime to remove anything from it! haha ha

Anyway thank you!

**Pull request closed without merging**
