### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by swajp**
Added new category with 2 links

---
name: feat: New category with 2 link

about: Inspo for people when thinking about new projects or 

labels: feature

---

## Describe the awesome thing you want to add

**What is it?** 

**What category does it belong to?** (Libs and Components, Apps, Ports, Design System, Boilerplates/Templates)

**Anything else? (optional)** (e.g. screenshots, additional information, etc.)

## Checklist

- [x] I checked that it is in alphabetical order.
- [x] I have checked that the awesome thing is not already listed.
- [x] I have provided a clear and concise description of the awesome thing.
- [x] I have provided a link to the awesome thing.
- [x] I have assigned the correct category to the awesome thing.

**Please note:** If you are adding a new category, you will need to create a new section in the `README.md` file. Please make sure to update the table of contents as well.

**Important:** The idea of this repository is to bring together free projects for open-source contributions. If the proposed addition is an entirely paid project, the PR will be closed.

### CODE REVIEW

**Comment by birobirobiro** [comment]
> Added new category with 2 links
> 
> name: feat: New category with 2 link
> 
> about: Inspo for people when thinking about new projects or
> 
> labels: feature
> 
> ## Describe the awesome thing you want to add
> **What is it?**
> 
> **What category does it belong to?** (Libs and Components, Apps, Ports, Design System, Boilerplates/Templates)
> 
> **Anything else? (optional)** (e.g. screenshots, additional information, etc.)
> 
> ## Checklist
> * [x]  I checked that it is in alphabetical order.
> * [x]  I have checked that the awesome thing is not already listed.
> * [x]  I have provided a clear and concise description of the awesome thing.
> * [x]  I have provided a link to the awesome thing.
> * [x]  I have assigned the correct category to the awesome thing.
> 
> **Please note:** If you are adding a new category, you will need to create a new section in the `README.md` file. Please make sure to update the table of contents as well.
> 
> **Important:** The idea of this repository is to bring together free projects for open-source contributions. If the proposed addition is an entirely paid project, the PR will be closed.

What do you think about creating a Websites and Porfolios Inspiration section? I think it would be better instead of Project & Portfolio Inspiration.

**Comment by swajp** [comment]
I agree with that. It sounds more better. I made new commit for change title

**Comment by birobirobiro** [comment]
> I agree with that. It sounds more better. I made new commit for change title

Maybe if we separated it into two sections it would be even better:

## Websites and Portfolio Inspirations:

### Websites:

- [godly](https://godly.website/) - Astronomically good web design inspiration. Only the best of the best.
- [list.swajp.me](https://list.swajp.me) - It has never been easier to find the right projects or designs by inspiring sucessful people.

### Portfolios:

- [birobirobiro.dev](https://birobirobiro.dev/)

---

Code example:

```mk
## Websites and Portfolio Inspirations:

### Websites:

- [godly](https://godly.website/) - Astronomically good web design inspiration. Only the best of the best.
- [list.swajp.me](https://list.swajp.me) - It has never been easier to find the right projects or designs by inspiring sucessful people.

### Portfolios:

- [birobirobiro.dev](https://birobirobiro.dev/)
```

**Comment by swajp** [comment]
Thats even better and less confusing! Can you add this to this PR or do I have to?

**Comment by birobirobiro** [comment]
> Thats even better and less confusing! Can you add this to this PR or do I have to?

You can make this change and then merge it, as in the suggested example.

**Comment by swajp** [comment]
Done. I also added my portfolio

**Pull request merged**
